version: '4'

services:

  php:
    image: php:7.4-apache
    container_name: meu-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - C:\Users\guilherme.neves\Documents\dockerphp:/var/www/html
    links:
      - db

  db: 
    image: mysql:8.0
    container_name: meu-mysql-php
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
